apiVersion: v1
kind: ConfigMap
metadata:
  name: telemd-config
  namespace: default
data:
  telemd_period_cpu: "1s"
  telemd_period_freq: "1s"
  telemd_period_ram: "1s"
  telemd_period_disk: "1s"
  telemd_period_net: "1s"
  telemd_period_load: "1s"
  telemd_period_procs: "1s"
  telemd_period_kubernetes_cgrp_cpu: "1s"
  telemd_period_kubernetes_cgrp_blkio: "1s"
  telemd_period_kubernetes_cgrp_memory: "1s"
  telemd_period_psi_cpu: "1s"
  telemd_period_psi_io: "1s"
  telemd_period_psi_memory: "1s"
  telemd_redis_url: redis-url
  telemd_instruments_disable: docker_cgrp_cpu docker_cgrp_net docker_cgrp_blkio
