apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telemd-gpu
  labels:
    app: telemd-gpu
spec:
  selector:
    matchLabels:
      app: telemd-gpu
  template:
    metadata:
      labels:
        app: telemd-gpu
    spec:
      nodeSelector:
        telemd.edgerun.io/mode: gpu
      hostNetwork: true
      volumes:
      - name: sys
        hostPath:
         path: /sys
      - name: proc
        hostPath:
         path: /proc
      containers:
      - name: telemd
        image: edgerun/telemd-gpu:0.9.5
        env:
        - name: telemd_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: telemd-config
        volumeMounts:
        - name: sys
          mountPath: /sys
        - name: proc
          mountPath: /proc_host
